apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-app
  namespace: dashboard-context
  labels:
    app: dashboard-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard-app
  template:
    metadata:
      labels:
        app: dashboard-app
    spec:
      containers:
      - name: dashboard-app
        image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"