apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
  namespace: dashboard-context
spec:
  type: LoadBalancer
  selector:
    app: dashboard-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80